### ISSUE TITLE
Unable to unmarshal RLP encoded Icon TransactionResult.

### ISSUE THREAD

**Issue by viveksharmapoudel** [icon-project/ibc-relay#200]
**Describe the bug**
Relay is not able to unmarshal rlp encoded icon transactionresult which is resulting in unwanted restart.

**To Reproduce**
Tx fee shared enabled transaction contain extra field in txresult "stepUsedDetails". Whenever, this field is present in a transaction relay is throwing nil pointer issue.

**Expected behavior**
Icon transaction may or may not have stepUsedDetails, relay should handle that.

**Additional context**
Breaking change found from below transaction hash on mainnet:
```
0x19c50a29b5f8f84f598c45ea1d3ea71f2b72c4590b1483a3b31fab13206ed182
```

**Comment by pragyanshrestha-ibriz** [comment]
Fixed on mainnet
