### ISSUE TITLE
Docker image of rly not being built

### ISSUE THREAD

**Issue by izyak** [icon-project/ibc-relay#213]
I cannot build the docker image of relayer on my machine.

Additional Info:
- [ ]  Some others using linux are not able to build it as well.
- [ ] No issues with mac.

**Comment by izyak** [comment]
Can be built after upgrading the cosmwasm version to 1.5.0

**Comment by debendraoli** [comment]
This has been fixed @DeepakBomjan can create a fix for ibc-relay.

**Comment by bcsainju** [comment]
https://github.com/icon-project/ibc-relay/pull/214 This PR should resolve the build issue.
